#!/bin/bash

# Change to match USB device
USB_ID=14cd:1212

# Change to match card size
DRIVE_SIZE_GB=14

# Path to image
IMAGE="build/tmp/deploy/images/raspberrypi0-wifi/core-image-minimal-raspberrypi0-wifi.rootfs.wic.bz2"

# WSL Attach 
if [ -n "$USB_ID" ]; then
    usbipd.exe attach --wsl -i $USB_ID
    sleep 2
fi

# Find the USB drive by size
DEVNAME=$(lsblk -b -d -o NAME,SIZE,RM | awk -v size=$((DRIVE_SIZE_GB*1024*1024*1024)) \
    '$2 >= size-1000000000 && $2 <= size+1000000000 && $3 == 1 {print $1}')

# Found?
if [ -z "$DEVNAME" ]; then
    echo "USB drive not found. Check DRIVE_SIZE_GB or mount the USB."
    exit 1
fi

# List details
lsblk -o NAME,SIZE,MODEL,TRAN /dev/$DEVNAME

# Confirm
echo "Are you sure you want to write $IMAGE to /dev/$DEVNAME?"
read -p "This will erase it! (y/n): " CONFIRM
if [ "$CONFIRM" != "y" ]; then
    echo "Aborting."
    exit 0
fi

# Write the image
EXT="${IMAGE##*.}"
case "$EXT" in

    img)
        sudo dd if="$IMAGE" of=/dev/$DEVNAME bs=1M status=progress conv=fsync
        ;;

    bz2)
        bunzip2 -c $IMAGE | sudo dd of=/dev/$DEVNAME bs=4M status=progress conv=fsync
        ;;

    *)
        echo "Unknown file type: $extension"
        exit 1
        ;;

esac

# Flush writes
sudo sync

# WSL detach
if [ -n "$USB_ID" ]; then
    sleep 2
    usbipd.exe detach -i $USB_ID
fi

echo "Done! USB image written successfully."
